import type { AuditLog, FamilyLink, HumanitarianCase, Person, Referral, SecurityEvent, ServicePoint, User } from "./types";

export const users: User[] = [
  { id: "u1", name: "Miriam Tesfaye", email: "admin@hpis.demo", role: "SUPER_ADMIN", mfaEnabled: true },
  { id: "u2", name: "Program Manager 02", email: "manager@hpis.demo", role: "PROGRAM_MANAGER", mfaEnabled: true },
  { id: "u3", name: "Protection Officer 04", email: "protection@hpis.demo", role: "PROTECTION_OFFICER", mfaEnabled: true },
  { id: "u4", name: "Case Worker 11", email: "caseworker@hpis.demo", role: "CASE_WORKER", mfaEnabled: false },
  { id: "u5", name: "Data Officer 03", email: "data@hpis.demo", role: "DATA_OFFICER", mfaEnabled: true },
  { id: "u6", name: "Field Officer 09", email: "field@hpis.demo", role: "FIELD_OFFICER", mfaEnabled: false },
  { id: "u7", name: "Read-only Auditor", email: "auditor@hpis.demo", role: "AUDITOR", mfaEnabled: true }
];

export const persons: Person[] = [
  { id: "PERSON-ET-000184", pseudonym: "Person A-184", restrictedName: "Synthetic Name A", ageRange: "18-25", sex: "Female", region: "Amhara", lastKnownLocation: "North Wollo", verificationStatus: "Pending" },
  { id: "PERSON-ET-000291", pseudonym: "Person B-291", restrictedName: "Synthetic Name B", ageRange: "26-35", sex: "Male", region: "Tigray", lastKnownLocation: "Mekelle", verificationStatus: "Unverified" },
  { id: "PERSON-ET-000377", pseudonym: "Person C-377", ageRange: "36-45", sex: "Unknown", region: "Oromia", lastKnownLocation: "East Shewa", verificationStatus: "Verified" },
  { id: "PERSON-ET-000418", pseudonym: "Person D-418", ageRange: "12-17", sex: "Female", region: "Afar", lastKnownLocation: "Semera", verificationStatus: "Pending" }
];

export const cases: HumanitarianCase[] = [
  { id: "HP-2026-00184", type: "FAMILY_SEPARATION", priority: "HIGH", region: "Amhara", location: "North Wollo", status: "INVESTIGATION", assignedOfficer: "Protection Officer 04", opened: "2026-08-11", updated: "2026-08-11", personId: "PERSON-ET-000184", summary: "Family separation case requiring tracing and psychosocial referral review.", notes: ["Initial intake completed with minimal required data.", "Consent notice acknowledged in demo workflow."] },
  { id: "HP-2026-00291", type: "MISSING_PERSON", priority: "CRITICAL", region: "Tigray", location: "Mekelle", status: "ASSESSMENT", assignedOfficer: "Protection Officer 04", opened: "2026-08-08", updated: "2026-08-10", personId: "PERSON-ET-000291", summary: "Missing-person tracing request with potential match pending human verification.", notes: ["Potential match generated by deterministic demo scoring."] },
  { id: "HP-2026-00377", type: "PROTECTION", priority: "MEDIUM", region: "Oromia", location: "East Shewa", status: "FOLLOW_UP", assignedOfficer: "Case Worker 11", opened: "2026-07-27", updated: "2026-08-09", personId: "PERSON-ET-000377", summary: "Protection follow-up with referral outcome pending.", notes: ["Follow-up appointment recorded offline and synchronized."] },
  { id: "HP-2026-00418", type: "ASSISTANCE", priority: "LOW", region: "Afar", location: "Semera", status: "REFERRAL", assignedOfficer: "Field Officer 09", opened: "2026-08-01", updated: "2026-08-07", personId: "PERSON-ET-000418", summary: "Assistance referral and service mapping demonstration.", notes: ["Fictional service directory used for demo only."] }
];

export const familyLinks: FamilyLink[] = [
  { id: "FL-2026-0184", caseId: "HP-2026-00184", personId: "PERSON-ET-000184", status: "POTENTIAL_MATCH", lastContact: "2026-07-19", circumstances: "Separated during movement between fictional locations.", matchScore: 87 },
  { id: "FL-2026-0291", caseId: "HP-2026-00291", personId: "PERSON-ET-000291", status: "VERIFICATION_REQUIRED", lastContact: "2026-07-02", circumstances: "Family contact lost after displacement.", matchScore: 78 }
];

export const referrals: Referral[] = [
  { id: "REF-00041", caseId: "HP-2026-00184", category: "Psychosocial", organization: "Partner Organization A", priority: "HIGH", date: "2026-08-11", status: "PENDING", outcome: "Awaiting acceptance" },
  { id: "REF-00042", caseId: "HP-2026-00377", category: "Protection", organization: "Partner Organization B", priority: "MEDIUM", date: "2026-08-09", status: "IN_PROGRESS", outcome: "Follow-up scheduled" },
  { id: "REF-00043", caseId: "HP-2026-00418", category: "Emergency Assistance", organization: "Partner Organization C", priority: "LOW", date: "2026-08-07", status: "ACCEPTED", outcome: "Demo distribution review" }
];

export const auditLogs: AuditLog[] = [
  { id: "AUD-1", user: "admin@hpis.demo", action: "CREATE_CASE", resource: "HP-2026-00184", timestamp: "2026-08-11 09:42", result: "SUCCESS" },
  { id: "AUD-2", user: "protection@hpis.demo", action: "VIEW_SENSITIVE_CASE", resource: "HP-2026-00184", timestamp: "2026-08-11 09:51", result: "SUCCESS" },
  { id: "AUD-3", user: "manager@hpis.demo", action: "EXPORT_REPORT", resource: "Monthly aggregate report", timestamp: "2026-08-11 10:04", result: "SUCCESS" },
  { id: "AUD-4", user: "data@hpis.demo", action: "VIEW_RESTRICTED_IDENTIFIER", resource: "PERSON-ET-000184", timestamp: "2026-08-11 10:09", result: "DENIED" },
  { id: "AUD-5", user: "admin@hpis.demo", action: "ENABLE_EMERGENCY_PRIVACY_MODE", resource: "System", timestamp: "2026-08-11 10:12", result: "SUCCESS" }
];

export const securityEvents: SecurityEvent[] = [
  { id: "SEC-1", type: "LOGIN_FAILURE", severity: "Medium", timestamp: "2026-08-11 08:22", status: "Reviewed" },
  { id: "SEC-2", type: "UNUSUAL_ACCESS", severity: "High", timestamp: "2026-08-11 09:17", status: "Investigating" },
  { id: "SEC-3", type: "DATA_EXPORT", severity: "Medium", timestamp: "2026-08-11 10:04", status: "Approved" },
  { id: "SEC-4", type: "PERMISSION_CHANGE", severity: "High", timestamp: "2026-08-11 10:12", status: "Logged" }
];

export const services: ServicePoint[] = [
  { id: "SVC-1", name: "Addis Ababa Demo Service Center", category: "Family Link", region: "Addis Ababa", lat: 9.03, lng: 38.74, hours: "08:30-17:00", services: "Tracing requests, family contact, referral" },
  { id: "SVC-2", name: "Amhara Demo Psychosocial Desk", category: "Psychosocial", region: "Amhara", lat: 11.6, lng: 37.38, hours: "09:00-16:00", services: "Psychosocial intake and follow-up" },
  { id: "SVC-3", name: "Oromia Demo Medical Referral Point", category: "Medical", region: "Oromia", lat: 8.56, lng: 39.27, hours: "08:00-18:00", services: "Medical referral information" },
  { id: "SVC-4", name: "Afar Demo Assistance Desk", category: "Assistance", region: "Afar", lat: 11.79, lng: 41.01, hours: "09:00-15:00", services: "Emergency assistance referral" }
];

export const caseTrend = [
  { name: "Apr", cases: 164, resolved: 92 },
  { name: "May", cases: 188, resolved: 121 },
  { name: "Jun", cases: 214, resolved: 139 },
  { name: "Jul", cases: 238, resolved: 158 },
  { name: "Aug", cases: 248, resolved: 184 }
];

export const regionCounts = [
  { name: "Amhara", value: 327 },
  { name: "Oromia", value: 281 },
  { name: "Tigray", value: 229 },
  { name: "Afar", value: 141 },
  { name: "Addis Ababa", value: 118 }
];
