name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'

    - name: Install dependencies (Frontend)
      run: npm install

    - name: Install dependencies (Backend)
      run: cd server && npm install

    - name: Run ESLint
      run: npm run lint

    - name: Test (Frontend)
      run: npm test

    - name: Test (Backend)
      run: cd server && npm test

    - name: Build (Frontend)
      run: npm run build
